### ISSUE TITLE
Require LearnBase

### ISSUE THREAD

**Issue by Evizero** [tbreloff/MLPlots.jl#1]
I will need to introduce a dependency on LearnBase. ~~LearnBase in turn currently has an dependency on MLDatasets which is not yet ready for METADATA~~

this should do the trick for now:

``` Julia
Pkg.clone("https://github.com/Evizero/LearnBase.jl")
```

**Comment by tbreloff** [comment]
I assume the MLDatasets dependency will be removed eventually, right?

**Comment by tbreloff** [comment]
I guess what I'm saying it that it seems like MLDatasets should depend on LearnBase, not the other way around.  Do you agree?

**Comment by Evizero** [comment]
Thinking about it I could actually turn it around and make MLDatasets depend on LearnBase

EDIT: I turned the dependencies around
