### ISSUE TITLE
corrplot doesn't support DataFrames

### ISSUE THREAD

**Issue by diegozea** [tbreloff/MLPlots.jl#10]
`LoadError: MethodError:`corrplot`has no method matching corrplot(::DataFrames.DataFrame)`

**Comment by tbreloff** [comment]
This should probably be a Plots issue... passing in a DataFrame to any plotting command, but without any column labels, should plot one series per column.

**Comment by s-celles** [comment]
I'm also facing same issue

``` julia
julia> using RDatasets
julia> using MLPlots
julia> iris=dataset("datasets", "iris")
julia> corrplot(iris)
ERROR: MethodError: `corrplot` has no method matching corrplot(::DataFrames.DataFrame)
```

Maybe you should add Requires.jl https://github.com/MikeInnes/Requires.jl to help to fix that

**Comment by tbreloff** [comment]
> This should probably be a Plots issue... passing in a DataFrame to any plotting command, but without any column labels, should plot one series per column.

To be clear... this isn't a bug... it's a not-yet-implemented feature.  I should note that I plan on rewriting corrplot as a "user recipe" and moving it to [PlotRecipes.jl](https://github.com/JuliaPlots/PlotRecipes.jl).

> Maybe you should add Requires.jl https://github.com/MikeInnes/Requires.jl to help to fix that

I'm not sure what you think that would accomplish...

**Comment by s-celles** [comment]
To my understanding if you add Requires.jl as requirement, you will be able to have code that can take DataFrame as input (even if DataFrames.jl is not installed). So it's a good way to have optional dependencies.

**Comment by tbreloff** [comment]
Yeah I know about Requires (btw DataFrames is already an optional
dependency). It just doesn't make any sense as a solution. We're just missing
a dataframe-specific feature.

**Comment by Evizero** [comment]
To me Requires seems like an unclean solution nowadays

**Comment by s-celles** [comment]
``` julia
a=Array(iris[[:SepalLength,:SepalWidth,:PetalLength,:PetalWidth]])
corrplot(a)
```

![capture d ecran 2016-06-09 a 15 50 53](https://cloud.githubusercontent.com/assets/109167/15931956/1b8c1a46-2e5a-11e6-82dd-a0b1620da770.png)

Unfortunatelly I haven't found a way to define points color by Species.

Setting axes name will also be a great feature to have.

A similar issue [can be found here](https://github.com/dcjones/Gadfly.jl/issues/286)

**Comment by tbreloff** [comment]
See: https://github.com/JuliaPlots/PlotRecipes.jl/issues/1

Any feature requests for the corrplot recipe should be made there.
